export const SET_USER_PLAYLIST_COLLECTION = 'SET_USER_PLAYLIST_COLLECTION';
export const SET_USER_SAVED_ALBUMS = 'SET_USER_SAVED_ALBUMS';
export const SET_USER_FOLLOWING_ARTISTS = 'SET_USER_FOLLOWING_ARTISTS';
export const SET_USER_ISFOLLOWING_STATUS = 'SET_USER_ISFOLLOWING_STATUS';
export const SET_USER_SAVED_TRACKS = 'SET_USER_SAVED_TRACKS';

export const SET_USER_BROWSE_NEWRELEASES = 'SET_USER_BROWSE_NEWRELEASES';
export const SET_USER_BROWSE_FEATUREDPLAYLISTS = 'SET_USER_BROWSE_FEATUREDPLAYLISTS';
export const SET_USER_BROWSE_CATEGORIES = 'SET_USER_BROWSE_CATEGORIES';
export const SET_USER_BROWSE_RECOMMENDATIONS = 'SET_USER_BROWSE_RECOMMENDATIONS';


export const ADD_SAVEDDATA_PLAYLISTS = 'ADD_SAVEDDATA_PLAYLISTS';
export const ADD_SAVEDDATA_ALBUMS = 'ADD_SAVEDDATA_ALBUMS';
export const ADD_SAVEDDATA_ARTISTS = 'ADD_SAVEDDATA_ARTISTS';
export const ADD_SAVEDDATA_ARTISTS_ALBUMS = 'ADD_SAVEDDATA_ARTISTS_ALBUMS';
export const ADD_SAVEDDATA_CATEGORIES = 'ADD_SAVEDDATA_CATEGORIES';
