export const SET_HEADER_BGCOLOR = "SET_HEADER_BGCOLOR";
export const SHOW_SEARCH_IN_HEADER = "SHOW_SEARCH_IN_HEADER";

export const SET_SEARCH_DETAILS_DATA = "SET_SEARCH_DETAILS_DATA";
export const SET_NUMBER_OF_CARDS = "SET_NUMBER_OF_CARDS";